### ISSUE TITLE
Simplify UI of iSEG

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-iseg#137]
Usability feedback of iSEG suggests that simplifying the UI will largely improve the user experience.

In my experience, showing by default only some sub-windows would be a good first step. What do you think @esraneufeld, @newton1985? If that is good, which ones?

cc @mguidon

**Comment by elisabettai** [comment]
This should already be better with v1.0.11, see changelog sent [here](https://mattermost.speag.com/z43/pl/umhtt1tbijd4zmxtcsofocf5kc). User can now configure the UI and the changes will be persistent.

**Comment by newton1985** [comment]
Hi @elisabettai,
The current solution is certainly not bad, but after discussing with @esraneufeld, we agreed that it makes sense to also have the default iSeg view more minimal than it currently is (rather than leaving all the responsibility to the user). I'm attaching screenshots of the desired layout (as setup by Esra). I'm cc'ing @dyollb and @mguidon as well - it was proposed that Bryn could rearrange some of the visual elements to decrease visual clutter as well. Would you mind re-opening this ticket?

![iseg_1](https://user-images.githubusercontent.com/70750341/198323989-e8069826-60a8-44b8-9134-20ab8204c043.jpg)
![iseg_2](https://user-images.githubusercontent.com/70750341/198323992-02141a15-3ba0-4c85-8b86-16841978d97c.jpg)
![iseg_3](https://user-images.githubusercontent.com/70750341/198323995-ad915cf0-740e-4a36-8e46-48545df15b4c.jpg)
